# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

# This is an example starter azure.yaml file containing several example services in comments below.
# Make changes as needed to describe your application setup.
# To learn more about the azure.yaml file, visit https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/azd-schema

# Name of the application.
name: apicenter-portal-starter
resourceGroup: ${AZURE_RESOURCE_GROUP_NAME}

metadata:
  template: api-center-portal

workflows:
  up: 
    steps:
      - azd: provision
      - azd: package --all
      - azd: deploy --all

services:
  staticapp-portal:
    language: ts
    project: ./
    host: staticwebapp
    dist: dist
    config:
      build:
        commands:
          - npm ci
          - npm run build
        outputLocation: dist
        appLocation: "/"

hooks:
  preup:
    posix:
      shell: sh
      run: infra/hooks/preup.sh
      continueOnError: false
      interactive: true
    windows:
      shell: pwsh
      run: infra/hooks/preup.ps1
      continueOnError: false
      interactive: true
  preprovision:
    posix:
      shell: sh
      run: infra/hooks/preprovision.sh
      continueOnError: false
      interactive: true
    windows:
      shell: pwsh
      run: infra/hooks/preprovision.ps1
      continueOnError: false
      interactive: true
  postprovision:
    posix:
      shell: sh
      run: infra/hooks/postprovision.sh
      continueOnError: false
      interactive: true
    windows:
      shell: pwsh
      run: infra/hooks/postprovision.ps1
      continueOnError: false
      interactive: true
  predeploy:
    posix:
      shell: sh
      run: infra/hooks/predeploy.sh
      continueOnError: true  # Changed to true for production safety
      interactive: false    # Changed to false for production
    windows:
      shell: pwsh
      run: infra/hooks/predeploy.ps1
      continueOnError: true  # Changed to true for production safety
      interactive: false    # Changed to false for production
  predown:
    posix:
      shell: sh
      continueOnError: false
      interactive: true
      run: infra/hooks/predown.sh
    windows:
      shell: pwsh
      continueOnError: false
      interactive: true
      run: infra/hooks/predown.ps1
